# Generated by Django 3.2.7 on 2021-09-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='intro',
            new_name='description',
        ),
        migrations.AddField(
            model_name='intro',
            name='title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
