# Generated by Django 3.2.7 on 2021-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210930_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intro',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
